version: '3'
services:
  app:
    container_name: todo_app
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:3000"
    entrypoint:
      - /usr/bin/tini
      - --
    command: yarn start:dev
    depends_on:
      - database
  database:
    container_name: todo_database
    image: mysql:8.0.32
    volumes:
      - mysql-db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}

  phpmyadmin:
    container_name: todo_pma
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_HOST: todo_database
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - database

volumes:
  mysql-db:
    driver: local
