FROM node:20.14.0-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get -qq install -y --no-install-recommends \
    tzdata \
    tini \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV development

COPY --chown=node:node package.json ./

RUN yarn --frozen-lockfile

COPY --chown=node:node ./src/db ./src/db
COPY --chown=node:node .env .env

USER node

CMD [ "yarn", "migration:run" ]