name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - develop
      - master

env:
  DATABASE_HOST: localhost
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_PORT: 3306
  DATABASE_DB: api
  JWT_SECRET_KEY: hoge

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: api
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --default-authentication-plugin=mysql_native_password
    steps:
      - name: Chekcout code
        uses: actions/checkout@v4
      - name: Install
        run: yarn install
      - name: Build Pages
        run: yarn api:create:doc
      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          # 絶対パスを指定
          path: docs

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
